version: '3.8'

services:
  smokex:
    build: .
    environment:
      - SECRET_KEY_BASE=kGXrNEYUVAm2zOpB8UQMRfK+JkDnqFcH4WOcM8nYApN/fMWVJoQPMGqrUTwv15w5
      - DATABASE_HOSTNAME=postgres-container
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DASHBOARD_AUTH_USERNAME="hey"
      - DASHBOARD_AUTH_PASSWORD="hey"
      - PORT=4000
      - POOL_SIZE=1
      - STRIPE_API_KEY=""
      - STRIPE_SIGNING_SECRET=""
      - STRIPE_PUBLISHABLE_API_KEY=""
      - STRIPE_PRICE_ID=""
      - SLACK_CLIENT_ID=""
      - SLACK_CLIENT_SECRET=""
    ports:
      - 4000:4000
    depends_on:
      - postgres
    container_name: smokex
    networks:
      - localhost
    #command:
      #- ./bin/smokex
      #- eval
      #- Smokex.Release.migrate

  postgres:
    image: postgres:9.6.11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    container_name: postgres-container
    networks:
      - localhost

networks:
  localhost:
    driver: bridge

